### ISSUE TITLE
Dependency Package Lists

### ISSUE THREAD

**Issue by uzzal2k5** [pol-is/polisDeployment#1]
Hi, Could you provide the package list for the following individually 

-> https://github.com/pol-is/polisServer

--> https://github.com/pol-is/polisMath

--> https://github.com/pol-is/polisClientAdmin

 --> https://github.com/pol-is/polisClientParticipati

**Comment by metasoarous** [comment]
In general, the JS projects should have all dependencies in the respective `package.json` files. For Clojure, the dependencies are in the `project.clj` file.

For system dependencies, obviously Node for the JS things, and Java for Clojure. But also a postgresql database and the postgresql client libs. More documentation on deployment and dev environment will be coming soon, so stay tuned.

**Comment by metasoarous** [comment]
@uzzal2k5 Also, we encourage users to submit issues through https://github.com/pol-is/issues to keep things centralized, and may start centralizing the "getting oriented" docs around there.
